[package]
name = "metime_core"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.38.0", features = ["rt", "macros"] }
rand = "0.8.5"
thiserror = "1.0.61"
chrono = "0.4.38"
chrono-tz = "0.8.6"
rrule = "=0.12.0"
